{
 "title": "Homework service",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Assignments resource - rate per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "application_pv217_AssignmentsResource_getAssignmentsTimer_one_min_rate_per_second",
     "legendFormat": "Get assignment"
    },
    {
     "expr": "application_pv217_AssignmentsResource_postAssignmentTimer_one_min_rate_per_second",
     "legendFormat": "Post assignment"
    }
   ]
  },
  {
   "title": "Solutions resource - rate per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "application_pv217_SolutionsResource_getSolutionsTimer_one_min_rate_per_second",
     "legendFormat": "Get solutions"
    },
    {
     "expr": "application_pv217_SolutionsResource_postSolutionTimer_one_min_rate_per_second",
     "legendFormat": "Post solution"
    },
    {
     "expr": "application_pv217_SolutionsResource_markSolutionTimer_one_min_rate_per_second",
     "legendFormat": "Mark solution"
    }
   ]
  },
  {
   "title": "Assignments resource",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_pv217_AssignmentsResource_getAssignments_total",
     "legendFormat": "Get assignments"
    },
    {
     "expr": "application_pv217_AssignmentsResource_postAssignment_total",
     "legendFormat": "Post assignment"
    }
   ]
  },
  {
   "title": "Solutions resource",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_pv217_SolutionsResource_getSolutions_total",
     "legendFormat": "Get solutions"
    },
    {
     "expr": "application_pv217_SolutionsResource_postSolution_total",
     "legendFormat": "Post solution"
    },
    {
     "expr": "application_pv217_SolutionsResource_markSolution_total",
     "legendFormat": "Mark solution"
    }
   ]
  }
 ]
}