---
openapi: 3.0.3
info:
  title: Email Service API
  description: Service for sending email notifications
  version: "1.0"
paths:
  /email/send:
    post:
      operationId: sendEmail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailMessage'
      responses:
        "201":
          description: Created
  /email/test:
    get:
      operationId: test
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Recipient:
      type: object
      properties:
        address:
          type: string
        type:
          $ref: '#/components/schemas/RecipientType'
    CollectionRecipient:
      type: array
      items:
        $ref: '#/components/schemas/Recipient'
    RecipientType:
      type: object
      properties:
        type:
          type: string
    EmailMessage:
      type: object
      properties:
        body:
          type: string
        from:
          type: string
        recipients:
          $ref: '#/components/schemas/CollectionRecipient'
        subject:
          type: string